### ISSUE TITLE
Discussion for Unpredictable Proposer Selection Policy

### ISSUE THREAD

**Issue by ian0371** [klaytn/kips#146]
This issue is created for discussions on introducing unpredictable proposer selection policy.

The block proposer is freshly calculated after finalizing every block.
The random seed is mixHash from KIP-114 (#114).

This issue number will be used as a KIP number.

**Comment by hyunsooda** [comment]
@jiseongnoh,

Continue [the thread](https://github.com/klaytn/kips/pull/147#discussion_r1243239111) from the last comment.

The expression 2f+1 can be interpreted in two ways: including the proposer or not including.

Case 1: If a proposer is in the committee and no other validator occupies its place.
Then my claim holds (i.e., 2f+1 -> 2f). This aligns with the current implementation because the proposer always provides a true answer. Therefore, I requested a counterexample to demonstrate a situation where the hypothesis is not true, but one was not provided.

Case 2: If a proposer is in the committee and another validator occupies its place.
The 2f+1 condition is now preserved if the hypothesis holds because the always-true answer was filtered out. (Say, I 'm a candidate of class president election and I have one vote. Then, it's so obvious)

Including the proposer in the 2f+1 condition does not increase the network's stability if the hypothesis holds because it is equivalent to just 2f. Can you provide a counterexample to support a different conclusion?

**Comment by jiseongnoh** [comment]
Consider a case of four validators where the proposer fails to send a commit message. This results in the necessity of the remaining three validators to achieve consensus, contradicting the assertion that only 2f validators are required if the proposer is excluded from the 2f+1 quorum.

This instance demonstrates the proposer's crucial role in consensus and underlines that excluding the proposer from the quorum could potentially disrupt consensus, particularly when some validators fail in their roles. 

Therefore, it stresses the need for the traditional 2f+1 condition, inclusive of the proposer, to maintain network stability and reliable consensus, despite potential validator failures.

**Comment by hyunsooda** [comment]
Proposition: The ongoing topic of discussion revolves around whether to include the proposer itself in the 2f+1 rule.

In your example, the failure appears quite evident because the proposition does not hold. In other words, the solution you presented is essentially the same as changing 2f+1 to 2f logically. If you disagree and believe that this is not 2f, could you provide a counterexample where the proposer disagrees with themselves?

Therefore, I repeatedly have doubts regarding the current implementation having a 2f policy instead of 2f+1, and I question the necessity of transitioning to 2f+1 in the future within a permissionless architecture.

**Comment by jiseongnoh** [comment]
In Round 1, the honest proposer (A) sends a block to Validators B, C, and D.

Validators B and C send a PREPARE message, while D does not. B and C reach the prepared state, with C moving into the committed state after receiving B's COMMIT message. However, B doesn't receive C's COMMIT message and therefore remains in the prepared state.

Validators A, B, and D, who have not committed, initiate a view change and proceed to Round 2. Validator C, who was in the committed state, isn't part of this as it believes consensus has already been achieved for the round.

In Round 2, B, as the new proposer, sends a block to Validators A and D. They all successfully move into the prepared and then committed state.

The issue that arises is that now we have Validator C, who believes that the block from Round 1 has been committed, and Validators A, B, and D, who believe that a different block (the block from Round 2) has been committed. This results in a chain split.

In a consensus protocol operating under the 2f+1 rule, this situation should be avoided as consensus should be reached by a majority (the 2f+1 validators) and a view change should only occur if the majority agrees that the proposer may be faulty. In this example, a view change was initiated without achieving consensus, resulting in a split.

This underlines the importance of considering edge cases and scenarios when deciding on consensus protocol rules. The 2f+1 rule, which includes the proposer in the consensus, aims to mitigate such issues and ensure consistency across the network.
